require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatabaseAlertsController do

  # This should return the minimal set of attributes required to create a valid
  # DatabaseAlert. As you add validations to DatabaseAlert, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatabaseAlertsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all database_alerts as @database_alerts" do
      database_alert = DatabaseAlert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:database_alerts).should eq([database_alert])
    end
  end

  describe "GET show" do
    it "assigns the requested database_alert as @database_alert" do
      database_alert = DatabaseAlert.create! valid_attributes
      get :show, {:id => database_alert.to_param}, valid_session
      assigns(:database_alert).should eq(database_alert)
    end
  end

  describe "GET new" do
    it "assigns a new database_alert as @database_alert" do
      get :new, {}, valid_session
      assigns(:database_alert).should be_a_new(DatabaseAlert)
    end
  end

  describe "GET edit" do
    it "assigns the requested database_alert as @database_alert" do
      database_alert = DatabaseAlert.create! valid_attributes
      get :edit, {:id => database_alert.to_param}, valid_session
      assigns(:database_alert).should eq(database_alert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DatabaseAlert" do
        expect {
          post :create, {:database_alert => valid_attributes}, valid_session
        }.to change(DatabaseAlert, :count).by(1)
      end

      it "assigns a newly created database_alert as @database_alert" do
        post :create, {:database_alert => valid_attributes}, valid_session
        assigns(:database_alert).should be_a(DatabaseAlert)
        assigns(:database_alert).should be_persisted
      end

      it "redirects to the created database_alert" do
        post :create, {:database_alert => valid_attributes}, valid_session
        response.should redirect_to(DatabaseAlert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved database_alert as @database_alert" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseAlert.any_instance.stub(:save).and_return(false)
        post :create, {:database_alert => {}}, valid_session
        assigns(:database_alert).should be_a_new(DatabaseAlert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseAlert.any_instance.stub(:save).and_return(false)
        post :create, {:database_alert => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested database_alert" do
        database_alert = DatabaseAlert.create! valid_attributes
        # Assuming there are no other database_alerts in the database, this
        # specifies that the DatabaseAlert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DatabaseAlert.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => database_alert.to_param, :database_alert => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested database_alert as @database_alert" do
        database_alert = DatabaseAlert.create! valid_attributes
        put :update, {:id => database_alert.to_param, :database_alert => valid_attributes}, valid_session
        assigns(:database_alert).should eq(database_alert)
      end

      it "redirects to the database_alert" do
        database_alert = DatabaseAlert.create! valid_attributes
        put :update, {:id => database_alert.to_param, :database_alert => valid_attributes}, valid_session
        response.should redirect_to(database_alert)
      end
    end

    describe "with invalid params" do
      it "assigns the database_alert as @database_alert" do
        database_alert = DatabaseAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_alert.to_param, :database_alert => {}}, valid_session
        assigns(:database_alert).should eq(database_alert)
      end

      it "re-renders the 'edit' template" do
        database_alert = DatabaseAlert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseAlert.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_alert.to_param, :database_alert => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested database_alert" do
      database_alert = DatabaseAlert.create! valid_attributes
      expect {
        delete :destroy, {:id => database_alert.to_param}, valid_session
      }.to change(DatabaseAlert, :count).by(-1)
    end

    it "redirects to the database_alerts list" do
      database_alert = DatabaseAlert.create! valid_attributes
      delete :destroy, {:id => database_alert.to_param}, valid_session
      response.should redirect_to(database_alerts_url)
    end
  end

end
